In [3]:
# Import libararies
import pandas as pd
import numpy as np

In [4]:
# Read data
df = pd.read_csv("performance_data_pipeline.csv")

In [5]:
# Display first 5 rows
df.head()

,CaseID,OfficerID,OfficerName,Team,DateCreated,DateClosed,Status,ResolutionHours,SLA_Target_Hours,SLA_Met,CSAT
0,1001,O004,Officer 4,Team B,2024-04-26,2024-04-27,Closed,36,48,Yes,3.9
1,1002,O005,Officer 5,Team C,2024-04-24,NaN,Open,73,48,NaN,NaN
2,1003,O005,Officer 5,Team C,2024-04-12,2024-04-14,Closed,60,48,No,4.7
3,1004,O003,Officer 3,Team B,2024-04-29,2024-05-02,Closed,74,48,No,4.3
4,1005,O003,Officer 3,Team B,2024-04-03,2024-04-03,Closed,16,48,Yes,4.3

In [6]:
# Display last 5 rows
df.tail()

,CaseID,OfficerID,OfficerName,Team,DateCreated,DateClosed,Status,ResolutionHours,SLA_Target_Hours,SLA_Met,CSAT
195,1196,O004,Officer 4,Team B,2024-04-20,NaN,Open,34,48,NaN,NaN
196,1197,O001,Officer 1,Team A,2024-04-22,2024-04-24,Closed,71,48,No,4.6
197,1198,O003,Officer 3,Team B,2024-04-25,2024-04-25,Closed,10,48,Yes,3.5
198,1199,O002,Officer 2,Team A,2024-04-15,2024-04-18,Closed,72,48,No,4.1
199,1200,O001,Officer 1,Team A,2024-04-11,2024-04-12,Closed,41,48,Yes,4.9

In [7]:
# Check data size
df.shape

(200, 11)

In [8]:
# Check all columns
df.columns

Index(['CaseID', 'OfficerID', 'OfficerName', 'Team', 'DateCreated',
       'DateClosed', 'Status', 'ResolutionHours', 'SLA_Target_Hours',
       'SLA_Met', 'CSAT'],
      dtype='object')

In [9]:
# Display all columns
pd.DataFrame(df.columns, columns=["Column Name"])

         Column Name
0             CaseID
1          OfficerID
2        OfficerName
3               Team
4        DateCreated
5         DateClosed
6             Status
7    ResolutionHours
8   SLA_Target_Hours
9            SLA_Met
10              CSAT

In [10]:
# Check data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CaseID            200 non-null    int64
 1   OfficerID         200 non-null    object
 2   OfficerName       200 non-null    object
 3   Team              200 non-null    object
 4   DateCreated       200 non-null    object
 5   DateClosed        183 non-null    object
 6   Status            200 non-null    object
 7   ResolutionHours   200 non-null    int64
 8   SLA_Target_Hours  200 non-null    int64
 9   SLA_Met           183 non-null    object
 10  CSAT              183 non-null    float64
dtypes: float64(1), int64(3), object(7)
memory usage: 17.3+ KB

- DateCreated and DateClosed are stored as object and should be converted to datetime during ETL.
- CSAT is numeric with missing values for open cases.

In [11]:
# Display summary statistics numeric columns
df.describe()

            CaseID  ResolutionHours  SLA_Target_Hours        CSAT
count   200.000000       200.000000             200.0  183.000000
mean   1100.500000        48.695000              48.0    4.299454
std      57.879185        27.208888               0.0    0.416487
min    1001.000000         2.000000              48.0    3.500000
25%    1050.750000        26.000000              48.0    4.000000
50%    1100.500000        49.000000              48.0    4.300000
75%    1150.250000        71.000000              48.0    4.700000
max    1200.000000        96.000000              48.0    5.000000

In [12]:
# Display summary statistics non-numeric columns
df.describe(include="all")

,CaseID,OfficerID,OfficerName,Team,DateCreated,DateClosed,Status,ResolutionHours,SLA_Target_Hours,SLA_Met,CSAT
count,200.000000,200,200,200,200,183,200,200.000000,200.0,183,183.000000
unique,NaN,5,5,3,30,32,2,NaN,NaN,2,NaN
top,NaN,O004,Officer 4,Team B,2024-04-20,2024-04-08,Closed,NaN,NaN,No,NaN
freq,NaN,44,44,83,14,10,183,NaN,NaN,92,NaN
mean,1100.500000,NaN,NaN,NaN,NaN,NaN,NaN,48.695000,48.0,NaN,4.299454
std,57.879185,NaN,NaN,NaN,NaN,NaN,NaN,27.208888,0.0,NaN,0.416487
min,1001.000000,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,48.0,NaN,3.500000
25%,1050.750000,NaN,NaN,NaN,NaN,NaN,NaN,26.000000,48.0,NaN,4.000000
50%,1100.500000,NaN,NaN,NaN,NaN,NaN,NaN,49.000000,48.0,NaN,4.300000
75%,1150.250000,NaN,NaN,NaN,NaN,NaN,NaN,71.000000,48.0,NaN,4.700000
max,1200.000000,NaN,NaN,NaN,NaN,NaN,NaN,96.000000,48.0,NaN,5.000000

In [13]:
# Check misisng values
df.isnull().sum()

CaseID               0
OfficerID            0
OfficerName          0
Team                 0
DateCreated          0
DateClosed          17
Status               0
ResolutionHours      0
SLA_Target_Hours     0
SLA_Met             17
CSAT                17
dtype: int64

In [14]:
# Check misisng values %
missing = (
    df.isnull().sum() / len(df) * 100
).round(2)

missing

CaseID              0.0
OfficerID           0.0
OfficerName         0.0
Team                0.0
DateCreated         0.0
DateClosed          8.5
Status              0.0
ResolutionHours     0.0
SLA_Target_Hours    0.0
SLA_Met             8.5
CSAT                8.5
dtype: float64

There are valid missing values (DateClosed, SLA_Met, CSAT) because open cases have not been resolved.

In [15]:
# Check missing data
df[df["DateClosed"].isna()]

,CaseID,OfficerID,OfficerName,Team,DateCreated,DateClosed,Status,ResolutionHours,SLA_Target_Hours,SLA_Met,CSAT
1,1002,O005,Officer 5,Team C,2024-04-24,NaN,Open,73,48,NaN,NaN
10,1011,O005,Officer 5,Team C,2024-04-16,NaN,Open,7,48,NaN,NaN
18,1019,O005,Officer 5,Team C,2024-04-27,NaN,Open,73,48,NaN,NaN
21,1022,O005,Officer 5,Team C,2024-04-16,NaN,Open,87,48,NaN,NaN
86,1087,O001,Officer 1,Team A,2024-04-27,NaN,Open,46,48,NaN,NaN
92,1093,O005,Officer 5,Team C,2024-04-09,NaN,Open,78,48,NaN,NaN
105,1106,O003,Officer 3,Team B,2024-04-17,NaN,Open,9,48,NaN,NaN
115,1116,O004,Officer 4,Team B,2024-04-28,NaN,Open,80,48,NaN,NaN
116,1117,O003,Officer 3,Team B,2024-04-08,NaN,Open,94,48,NaN,NaN
157,1158,O004,Officer 4,Team B,2024-04-29,NaN,Open,67,48,NaN,NaN
171,1172,O003,Officer 3,Team B,2024-04-23,NaN,Open,68,48,NaN,NaN
179,1180,O001,Officer 1,Team A,2024-04-23,NaN,Open,8,48,NaN,NaN
186,1187,O003,Officer 3,Team B,2024-04-27,NaN,Open,71,48,NaN,NaN
190,1191,O004,Officer 4,Team B,2024-04-25,NaN,Open,19,48,NaN,NaN
191,1192,O004,Officer 4,Team B,2024-04-22,NaN,Open,5,48,NaN,NaN
194,1195,O002,Officer 2,Team A,2024-04-30,NaN,Open,76,48,NaN,NaN
195,1196,O004,Officer 4,Team B,2024-04-20,NaN,Open,34,48,NaN,NaN

In [16]:
# Check missing data
df[df["CSAT"].isna()]

,CaseID,OfficerID,OfficerName,Team,DateCreated,DateClosed,Status,ResolutionHours,SLA_Target_Hours,SLA_Met,CSAT
1,1002,O005,Officer 5,Team C,2024-04-24,NaN,Open,73,48,NaN,NaN
10,1011,O005,Officer 5,Team C,2024-04-16,NaN,Open,7,48,NaN,NaN
18,1019,O005,Officer 5,Team C,2024-04-27,NaN,Open,73,48,NaN,NaN
21,1022,O005,Officer 5,Team C,2024-04-16,NaN,Open,87,48,NaN,NaN
86,1087,O001,Officer 1,Team A,2024-04-27,NaN,Open,46,48,NaN,NaN
92,1093,O005,Officer 5,Team C,2024-04-09,NaN,Open,78,48,NaN,NaN
105,1106,O003,Officer 3,Team B,2024-04-17,NaN,Open,9,48,NaN,NaN
115,1116,O004,Officer 4,Team B,2024-04-28,NaN,Open,80,48,NaN,NaN
116,1117,O003,Officer 3,Team B,2024-04-08,NaN,Open,94,48,NaN,NaN
157,1158,O004,Officer 4,Team B,2024-04-29,NaN,Open,67,48,NaN,NaN
171,1172,O003,Officer 3,Team B,2024-04-23,NaN,Open,68,48,NaN,NaN
179,1180,O001,Officer 1,Team A,2024-04-23,NaN,Open,8,48,NaN,NaN
186,1187,O003,Officer 3,Team B,2024-04-27,NaN,Open,71,48,NaN,NaN
190,1191,O004,Officer 4,Team B,2024-04-25,NaN,Open,19,48,NaN,NaN
191,1192,O004,Officer 4,Team B,2024-04-22,NaN,Open,5,48,NaN,NaN
194,1195,O002,Officer 2,Team A,2024-04-30,NaN,Open,76,48,NaN,NaN
195,1196,O004,Officer 4,Team B,2024-04-20,NaN,Open,34,48,NaN,NaN

In [17]:
# Check missing data from open status
df[df["DateClosed"].isna()]["Status"].value_counts()

Status
Open    17
Name: count, dtype: int64

In [18]:
# Check missing data all columns
df[df["DateClosed"].isna()][["CaseID","Status","DateClosed","SLA_Met","CSAT"]]

     CaseID Status DateClosed SLA_Met  CSAT
1      1002   Open        NaN     NaN   NaN
10     1011   Open        NaN     NaN   NaN
18     1019   Open        NaN     NaN   NaN
21     1022   Open        NaN     NaN   NaN
86     1087   Open        NaN     NaN   NaN
92     1093   Open        NaN     NaN   NaN
105    1106   Open        NaN     NaN   NaN
115    1116   Open        NaN     NaN   NaN
116    1117   Open        NaN     NaN   NaN
157    1158   Open        NaN     NaN   NaN
171    1172   Open        NaN     NaN   NaN
179    1180   Open        NaN     NaN   NaN
186    1187   Open        NaN     NaN   NaN
190    1191   Open        NaN     NaN   NaN
191    1192   Open        NaN     NaN   NaN
194    1195   Open        NaN     NaN   NaN
195    1196   Open        NaN     NaN   NaN

In [19]:
# Count open cases
(df["Status"] == "Open").sum()

np.int64(17)

In [20]:
# Count the number of missing values in the column
df["DateClosed"].isna().sum()

np.int64(17)

In [21]:
# Count the number of missing values in the column
df["SLA_Met"].isna().sum()

np.int64(17)

In [22]:
# Count the number of missing values in the column
df["CSAT"].isna().sum()

np.int64(17)

In [23]:
# Check dupicates rows
df.duplicated().sum()

np.int64(0)

In [24]:
# # Check dupicates case ids
df["CaseID"].duplicated().sum()

np.int64(0)

In [25]:
# Check unique values
df["Status"].unique()

array(['Closed', 'Open'], dtype=object)

In [26]:
# Check case ids
df["CaseID"].nunique()

200

In [27]:
# Verify case ids to ensure both numbers match from df["CaseID"].nunique()
len(df)

200

In [28]:
# Check unique values
df["Team"].unique()

array(['Team B', 'Team C', 'Team A'], dtype=object)

In [29]:
# Check unique values
df["OfficerName"].unique()

array(['Officer 4', 'Officer 5', 'Officer 3', 'Officer 1', 'Officer 2'],
      dtype=object)

In [30]:
# Check unique values
df["SLA_Met"].unique()

array(['Yes', nan, 'No'], dtype=object)

In [31]:
# Check unique values
df["SLA_Target_Hours"].unique()

array([48])

In [32]:
# # Count values
df["Status"].value_counts()

Status
Closed    183
Open       17
Name: count, dtype: int64

In [33]:
# Count values
df["Team"].value_counts()

Team
Team B    83
Team A    75
Team C    42
Name: count, dtype: int64

In [34]:
# Count values
df["OfficerName"].value_counts()

OfficerName
Officer 4    44
Officer 5    42
Officer 3    39
Officer 2    39
Officer 1    36
Name: count, dtype: int64

In [35]:
# Count values
df["SLA_Met"].value_counts(dropna=False)

SLA_Met
No     92
Yes    91
NaN    17
Name: count, dtype: int64

In [36]:
# # Count values
df["SLA_Target_Hours"].value_counts()

SLA_Target_Hours
48    200
Name: count, dtype: int64

In [37]:
# Check invalid values to ensure no negative
df["ResolutionHours"].min()

2

In [38]:
# Check invalid values to ensure no negative ensure empty dataframe
df[df["ResolutionHours"] < 0]

Empty DataFrame
Columns: [CaseID, OfficerID, OfficerName, Team, DateCreated, DateClosed, Status, ResolutionHours, SLA_Target_Hours, SLA_Met, CSAT]
Index: []

In [39]:
# Check invalid values within the range to ensure empty dataframe
df[
    (df["CSAT"] < 1) |
    (df["CSAT"] > 5)
]

Empty DataFrame
Columns: [CaseID, OfficerID, OfficerName, Team, DateCreated, DateClosed, Status, ResolutionHours, SLA_Target_Hours, SLA_Met, CSAT]
Index: []

In [40]:
# Find average resolution hours
df["ResolutionHours"].mean()

np.float64(48.695)

In [41]:
# Find average CSAT
df["CSAT"].mean()

np.float64(4.299453551912568)

In [42]:
# Check every officer belong to only one team
df.groupby("OfficerName")["Team"].nunique()

OfficerName
Officer 1    1
Officer 2    1
Officer 3    1
Officer 4    1
Officer 5    1
Name: Team, dtype: int64