In [49]:
# Import libararies
import pandas as pd
import numpy as np

In [50]:
# Read data
df = pd.read_csv("performance_data_pipeline.csv")

In [51]:
# Display data
df

,CaseID,OfficerID,OfficerName,Team,DateCreated,DateClosed,Status,ResolutionHours,SLA_Target_Hours,SLA_Met,CSAT
0,1001,O004,Officer 4,Team B,2024-04-26,2024-04-27,Closed,36,48,Yes,3.9
1,1002,O005,Officer 5,Team C,2024-04-24,NaN,Open,73,48,NaN,NaN
2,1003,O005,Officer 5,Team C,2024-04-12,2024-04-14,Closed,60,48,No,4.7
3,1004,O003,Officer 3,Team B,2024-04-29,2024-05-02,Closed,74,48,No,4.3
4,1005,O003,Officer 3,Team B,2024-04-03,2024-04-03,Closed,16,48,Yes,4.3
...,...,...,...,...,...,...,...,...,...,...,...
195,1196,O004,Officer 4,Team B,2024-04-20,NaN,Open,34,48,NaN,NaN
196,1197,O001,Officer 1,Team A,2024-04-22,2024-04-24,Closed,71,48,No,4.6
197,1198,O003,Officer 3,Team B,2024-04-25,2024-04-25,Closed,10,48,Yes,3.5
198,1199,O002,Officer 2,Team A,2024-04-15,2024-04-18,Closed,72,48,No,4.1
199,1200,O001,Officer 1,Team A,2024-04-11,2024-04-12,Closed,41,48,Yes,4.9

In [52]:
# Check data size
df.shape

(200, 11)

In [53]:
# Check data types
df.dtypes

CaseID                int64
OfficerID            object
OfficerName          object
Team                 object
DateCreated          object
DateClosed           object
Status               object
ResolutionHours       int64
SLA_Target_Hours      int64
SLA_Met              object
CSAT                float64
dtype: object

In [54]:
# Verify data types after converting
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CaseID            200 non-null    int64
 1   OfficerID         200 non-null    object
 2   OfficerName       200 non-null    object
 3   Team              200 non-null    object
 4   DateCreated       200 non-null    object
 5   DateClosed        183 non-null    object
 6   Status            200 non-null    object
 7   ResolutionHours   200 non-null    int64
 8   SLA_Target_Hours  200 non-null    int64
 9   SLA_Met           183 non-null    object
 10  CSAT              183 non-null    float64
dtypes: float64(1), int64(3), object(7)
memory usage: 17.3+ KB

In [55]:
# Convert datatypes from object to datetime
df["DateCreated"] = pd.to_datetime(df["DateCreated"])

In [56]:
# Convert datatypes from object to datetime
df["DateClosed"] = pd.to_datetime(df["DateClosed"])

In [57]:
# Verify datatypes after converting
df.dtypes

CaseID                       int64
OfficerID                   object
OfficerName                 object
Team                        object
DateCreated         datetime64[ns]
DateClosed          datetime64[ns]
Status                      object
ResolutionHours              int64
SLA_Target_Hours             int64
SLA_Met                     object
CSAT                       float64
dtype: object

In [58]:
# Check duplicates
df.duplicated().sum()

# Remove df = df.drop_duplicates()

np.int64(0)

In [59]:
# Check missing values - do not need to remove due to open case ids
df.isnull().sum()

CaseID               0
OfficerID            0
OfficerName          0
Team                 0
DateCreated          0
DateClosed          17
Status               0
ResolutionHours      0
SLA_Target_Hours     0
SLA_Met             17
CSAT                17
dtype: int64

In [60]:
# Fill SLA_Met column with pending
df["SLA_Met"] = df["SLA_Met"].fillna("Pending")

# Check SLA_Met column after filled with pending
df["SLA_Met"].value_counts(dropna=False)

SLA_Met
No         92
Yes        91
Pending    17
Name: count, dtype: int64

In [61]:
# Fill CSAT column with 0
df["CSAT"] = df["CSAT"].fillna(0)

# Check CSAT column after filled with 0
df[["Status", "CSAT"]].head(10)

   Status  CSAT
0  Closed   3.9
1    Open   0.0
2  Closed   4.7
3  Closed   4.3
4  Closed   4.3
5  Closed   4.8
6  Closed   4.2
7  Closed   4.9
8  Closed   3.7
9  Closed   4.5

In [62]:
# Find resolution days
df["ResolutionDays"] = (
    df["ResolutionHours"] / 24
).round(2)

In [63]:
# Create resolution days
df["ResolutionDays"] = (
    df["DateClosed"] - df["DateCreated"]
).dt.days


# Check columns
df[["DateCreated","DateClosed","ResolutionDays"]].head()

  DateCreated DateClosed  ResolutionDays
0  2024-04-26 2024-04-27             1.0
1  2024-04-24        NaT             NaN
2  2024-04-12 2024-04-14             2.0
3  2024-04-29 2024-05-02             3.0
4  2024-04-03 2024-04-03             0.0

In [64]:
# Create month
df["Month"] = df["DateCreated"].dt.month_name()

# Check column
df["Month"].head()

0    April
1    April
2    April
3    April
4    April
Name: Month, dtype: object

In [65]:
# Create year
df["Year"] = df["DateCreated"].dt.year

# Check column
df["Year"].unique()

array([2024], dtype=int32)

In [66]:
# Create day name
df["Day"] = df["DateCreated"].dt.day_name()

# Check column
df[["DateCreated", "Day"]].head()

  DateCreated        Day
0  2024-04-26     Friday
1  2024-04-24  Wednesday
2  2024-04-12     Friday
3  2024-04-29     Monday
4  2024-04-03  Wednesday

In [67]:
# Create week
df["Week"] = df["DateCreated"].dt.isocalendar().week

# Check column
df[["DateCreated","Week"]].head()

  DateCreated  Week
0  2024-04-26    17
1  2024-04-24    17
2  2024-04-12    15
3  2024-04-29    18
4  2024-04-03    14

In [68]:
# Check new columns
df.head()

,CaseID,OfficerID,OfficerName,Team,DateCreated,DateClosed,Status,ResolutionHours,SLA_Target_Hours,SLA_Met,CSAT,ResolutionDays,Month,Year,Day,Week
0,1001,O004,Officer 4,Team B,2024-04-26,2024-04-27,Closed,36,48,Yes,3.9,1.0,April,2024,Friday,17
1,1002,O005,Officer 5,Team C,2024-04-24,NaT,Open,73,48,Pending,0.0,NaN,April,2024,Wednesday,17
2,1003,O005,Officer 5,Team C,2024-04-12,2024-04-14,Closed,60,48,No,4.7,2.0,April,2024,Friday,15
3,1004,O003,Officer 3,Team B,2024-04-29,2024-05-02,Closed,74,48,No,4.3,3.0,April,2024,Monday,18
4,1005,O003,Officer 3,Team B,2024-04-03,2024-04-03,Closed,16,48,Yes,4.3,0.0,April,2024,Wednesday,14

In [69]:
# Create new columns
df["Month"] = df["DateCreated"].dt.month_name()

In [70]:
# Create new columns
df["Year"] = df["DateCreated"].dt.year

In [71]:
# Create case age
today = pd.Timestamp.today()

df["CaseAge"] = np.where(

    df["Status"]=="Closed",

    (df["DateClosed"]-df["DateCreated"]).dt.days,

    (today-df["DateCreated"]).dt.days

)

In [72]:
# Create SLA %
df["SLA_Met_Flag"] = (
    df["SLA_Met"]
      .map({
          "Yes":1,
          "No":0
      })
)

In [73]:
# Create CSAT category
df["CSAT_Category"] = pd.cut(

    df["CSAT"],

    bins=[0,4,4.5,5],

    labels=[

        "Low",

        "Medium",

        "High"

    ]

)

In [74]:
# Create resolution category
df["Resolution_Category"] = pd.cut(

    df["ResolutionHours"],

    bins=[0,24,48,72,100],

    labels=[

        "<24 hrs",

        "24-48 hrs",

        "49-72 hrs",

        ">72 hrs"

    ]

)

In [75]:
# Create team KPI summary
df["Resolution_Category"] = pd.cut(

    df["ResolutionHours"],

    bins=[0,24,48,72,100],

    labels=[

        "<24 hrs",

        "24-48 hrs",

        "49-72 hrs",

        ">72 hrs"

    ]

)

In [76]:
# Create officer KPI summary
officer_summary = (

    df

    .groupby("OfficerName")

    .agg(

        Cases=("CaseID","count"),

        AvgResolution=("ResolutionHours","mean"),

        AvgCSAT=("CSAT","mean")

    )

)

officer_summary

             Cases  AvgResolution   AvgCSAT
OfficerName
Officer 1       36      48.361111  4.061111
Officer 2       39      50.179487  4.284615
Officer 3       39      48.717949  3.789744
Officer 4       44      43.636364  3.818182
Officer 5       42      52.880952  3.754762

In [77]:
# Check data after adding new columns
df.head()

,CaseID,OfficerID,OfficerName,Team,DateCreated,DateClosed,Status,ResolutionHours,SLA_Target_Hours,SLA_Met,CSAT,ResolutionDays,Month,Year,Day,Week,CaseAge,SLA_Met_Flag,CSAT_Category,Resolution_Category
0,1001,O004,Officer 4,Team B,2024-04-26,2024-04-27,Closed,36,48,Yes,3.9,1.0,April,2024,Friday,17,1.0,1.0,Low,24-48 hrs
1,1002,O005,Officer 5,Team C,2024-04-24,NaT,Open,73,48,Pending,0.0,NaN,April,2024,Wednesday,17,812.0,NaN,NaN,>72 hrs
2,1003,O005,Officer 5,Team C,2024-04-12,2024-04-14,Closed,60,48,No,4.7,2.0,April,2024,Friday,15,2.0,0.0,High,49-72 hrs
3,1004,O003,Officer 3,Team B,2024-04-29,2024-05-02,Closed,74,48,No,4.3,3.0,April,2024,Monday,18,3.0,0.0,Medium,>72 hrs
4,1005,O003,Officer 3,Team B,2024-04-03,2024-04-03,Closed,16,48,Yes,4.3,0.0,April,2024,Wednesday,14,0.0,1.0,Medium,<24 hrs

In [78]:
# Save data
df.to_csv("performance_data_pipeline_cleaned.csv", index=False)

In [79]:
# Download
from google.colab import files

files.download("performance_data_pipeline_cleaned.csv")